apiVersion: "dse.database.datastax.com/v1beta2"
kind: "CassandraCluster"
metadata:
  name: "example-cassandra-cluster"
spec:
  size: 3
  version: "5.1.6"
  pod:
    resources:
      requests:
        memory: "4000Mi"
    dseEnv:
    - name: product 
      value: dse
    - name: PERSON
      value: gilbert 
